import Constants from "expo-constants";
import { Dimensions } from "react-native";

const SCALE = 375 / Dimensions.get("screen").width;

const styles = {
  appContainer: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#3C3C3C",
    paddingTop: Platform.OS === "android" ? Constants.statusBarHeight : 0,
  },
  scrollview: {
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    paddingBottom: 25 / SCALE,
  },
  hometitles: {
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 24 / SCALE,
    lineHeight: 28 / SCALE,
  },
  top10: { marginTop: 10 / SCALE },
  top20: { marginTop: 20 / SCALE },
  top48: { marginTop: 48 / SCALE },
  top55: { marginTop: 55 / SCALE },
  Top26: { top: 26 / SCALE },
  Top34: { top: 34 / SCALE },
  Top45: { top: 45 / SCALE },
  Top55: { top: 55 / SCALE },
  top132: { position: "absolute", top: 132 / SCALE },
  bottom15: { marginBottom: 15 / SCALE },
  width320: { width: 320 / SCALE },
  l100t10: { left: -100 / SCALE, marginTop: 10 / SCALE },
  l100t20: { left: -100 / SCALE, marginTop: 20 / SCALE },
  t200l20: { position: "absolute", top: 200 / SCALE, left: 20 / SCALE },
  l20t68: { position: "absolute", left: 20 / SCALE, top: 68 / SCALE },
  t10h40: { top: 10 / SCALE, height: 40 / SCALE },
  font10: {
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 10 / SCALE,
    lineHeight: 12 / SCALE,
  },
  font13: {
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 13 / SCALE,
    lineHeight: 15 / SCALE,
  },
  font20: {
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 20 / SCALE,
    lineHeight: 23 / SCALE,
  },
  font24: {
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 24 / SCALE,
    lineHeight: 28 / SCALE,
  },
  titletitle: {
    height: 40 / SCALE,
    width: 375 / SCALE,
    left: 15 / SCALE,
    top: 5 / SCALE,
  },
  titleprogresspos: {
    position: "absolute",
    width: 182 / SCALE,
    height: 40 / SCALE,
  },
  titlefitpos: {
    position: "absolute",
    left: 180 / SCALE,
    width: 60 / SCALE,
    height: 40 / SCALE,
  },
  titleprogress: {
    fontFamily: "WorkSans-Regular",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: 34 / SCALE,
    lineHeight: 40 / SCALE,
    textShadowColor: "rgba(66, 255, 255, 0.4)",
    textShadowOffset: { width: -1, height: -1 },
    textShadowRadius: 4,
  },
  titleprogressShadow: {
    fontFamily: "WorkSans-Regular",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: 34 / SCALE,
    lineHeight: 40 / SCALE,
    textShadowColor: "rgba(255, 192, 66, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
  },
  titlefit: {
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    width: 60 / SCALE,
    fontSize: 34 / SCALE,
    lineHeight: 40 / SCALE,
  },
  calendarcontainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    paddingTop: 13 / SCALE,
    paddingRight: 20 / SCALE,
    paddingBottom: 20 / SCALE,
    paddingLeft: 20 / SCALE,
  },
  calendartitle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 2 / SCALE,
    paddingRight: 10 / SCALE,
    paddingBottom: 2 / SCALE,
    paddingLeft: 10 / SCALE,
    width: 260 / SCALE,
    height: 39 / SCALE,
    backgroundColor: "#464646",
    borderRadius: 10 / SCALE,
  },
  calendarmonth: {
    width: 116 / SCALE,
    height: 28 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 24 / SCALE,
    lineHeight: 28 / SCALE,
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#FFFFFF",
    marginHorizontal: 10 / SCALE,
  },
  calendararrow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 45 / SCALE,
    height: 35 / SCALE,
    backgroundColor: "#464646",
  },
  weektitlecontainer: {
    height: 38 / SCALE,
    width: 258 / SCALE,
    marginTop: 5 / SCALE,
    display: "flex",
    flexDirection: "row",
  },
  daycontainer: {
    width: 30 / SCALE,
    height: 30 / SCALE,
    borderRadius: 8 / SCALE,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  daynumber: {
    fontFamily: "WorkSans-Bold",
    fontStyle: "normal",
    fontWeight: "900",
    fontSize: 15 / SCALE,
    lineHeight: 20 / SCALE,
    width: 20 / SCALE,
    height: 20 / SCALE,
    textAlign: "center",
    color: "#454545",
  },
  workoutspluscontainer: {
    display: "flex",
    alignItems: "center",
    paddingVertical: 12 / SCALE,
  },
  workoutsplus: {
    width: 50 / SCALE,
    height: 50 / SCALE,
    resizeMode: "cover",
  },
  workouttrailertitle: {
    position: "absolute",
    width: 106 / SCALE,
    height: 18 / SCALE,
    left: 10 / SCALE,
    top: 10 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 15 / SCALE,
    lineHeight: 18 / SCALE,
    color: "white",
    textAlign: "center",
  },
  workouttrailercolor: {
    position: "absolute",
    width: 100 / SCALE,
    height: 15 / SCALE,
    left: 188 / SCALE,
    top: 12 / SCALE,
    borderRadius: 7 / SCALE,
  },
  workouttrailerdumbbell: {
    position: "absolute",
    top: 48 / SCALE,
    left: 18 / SCALE,
    width: 20 / SCALE,
    height: 14 / SCALE,
  },
  workouttrailerexercises: {
    position: "absolute",
    width: 74 / SCALE,
    height: 14 / SCALE,
    left: 46 / SCALE,
    top: 48 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 12 / SCALE,
    lineHeight: 14 / SCALE,
    color: "white",
    textAlign: "center",
  },
  workouttrailerrecent: {
    position: "absolute",
    width: 39 / SCALE,
    height: 14 / SCALE,
    left: 170 / SCALE,
    top: 48 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 12 / SCALE,
    lineHeight: 14 / SCALE,
    color: "white",
  },
  workouttrailertimer: {
    position: "absolute",
    top: 48 / SCALE,
    left: 217 / SCALE,
    height: 14 / SCALE,
    width: 14 / SCALE,
  },
  workouttrailertime: {
    position: "absolute",
    width: 57 / SCALE,
    height: 14 / SCALE,
    left: 238 / SCALE,
    top: 48 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 12 / SCALE,
    lineHeight: 14 / SCALE,
    color: "white",
  },
  physiquebmi: {
    position: "absolute",
    width: 38 / SCALE,
    height: 23 / SCALE,
    left: 15 / SCALE,
    top: 15 / SCALE,
  },
  physiquegradient: {
    width: 280 / SCALE,
    height: 10 / SCALE,
    borderRadius: 5 / SCALE,
    marginTop: 22 / SCALE,
  },
  physiquecircle: {
    position: "absolute",
    top: 156 / SCALE,
  },
  physiquebmitext: {
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 14 / SCALE,
    lineHeight: 16 / SCALE,
    color: "white",
    marginTop: 3 / SCALE,
    textAlign: "center",
  },
  physiquebody: {
    left: 15 / SCALE,
    top: 200 / SCALE,
    width: 50 / SCALE,
    height: 23 / SCALE,
    position: "absolute",
  },
  physiquesettings: {
    position: "absolute",
    width: 30 / SCALE,
    height: 30 / SCALE,
    left: 251 / SCALE,
    top: 197 / SCALE,
  },
  measureword: {
    position: "absolute",
    height: 21 / SCALE,
    top: 10 / SCALE,
    left: 15 / SCALE,
    width: 130 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 18 / SCALE,
    lineHeight: 21 / SCALE,
    color: "white",
  },
  measureinput: {
    position: "absolute",
    textAlign: "right",
    height: 40 / SCALE,
    right: 50 / SCALE,
    width: 80 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 18 / SCALE,
    lineHeight: 21 / SCALE,
    color: "white",
  },
  measuremes: {
    position: "absolute",
    height: 21 / SCALE,
    right: 15 / SCALE,
    width: 30 / SCALE,
    top: 10 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 18 / SCALE,
    lineHeight: 21 / SCALE,
    color: "white",
    textAlign: "center",
  },
  workoutpagebody: {
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    width: 375 / SCALE,
    marginTop: 20 / SCALE,
  },
  workoutpageprogress: {
    position: "absolute",
    left: 192 / SCALE,
    top: 196 / SCALE,
  },
  workoutpageexercise: {
    position: "absolute",
    top: 241 / SCALE,
  },
  workoutpageplusc: {
    position: "absolute",
    bottom: 13 / SCALE,
  },
  workoutpageplus: {
    width: 45 / SCALE,
    height: 45 / SCALE,
    resizeMode: "cover",
  },
  nametitle: {
    position: "absolute",
    width: 250 / SCALE,
    height: 40 / SCALE,
    left: 20 / SCALE,
    top: 10 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 24 / SCALE,
    lineHeight: 28 / SCALE,
    textAlign: "left",
    color: "white",
  },
  namepen: {
    position: "absolute",
    top: 24 / SCALE,
    width: 20 / SCALE,
    height: 20 / SCALE,
    left: 273 / SCALE,
  },
  namedumbbell: {
    position: "absolute",
    top: 108 / SCALE,
    left: 21 / SCALE,
    width: 20 / SCALE,
    height: 14 / SCALE,
  },
  nameexercises: {
    position: "absolute",
    width: 74 / SCALE,
    height: 14 / SCALE,
    left: 47 / SCALE,
    top: 108 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 12 / SCALE,
    lineHeight: 14 / SCALE,
    color: "white",
    textAlign: "center",
  },
  namerecent: {
    position: "absolute",
    width: 39 / SCALE,
    height: 14 / SCALE,
    left: 172 / SCALE,
    top: 108 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 12 / SCALE,
    lineHeight: 14 / SCALE,
    color: "white",
  },
  nametimer: {
    position: "absolute",
    top: 108 / SCALE,
    left: 217 / SCALE,
    height: 14 / SCALE,
    width: 14 / SCALE,
  },
  nametime: {
    position: "absolute",
    width: 57 / SCALE,
    height: 14 / SCALE,
    left: 237 / SCALE,
    top: 108 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 12 / SCALE,
    lineHeight: 14 / SCALE,
    color: "white",
  },
  progresscanvas: {
    width: 110 / SCALE,
    height: 30 / SCALE,
  },
  progresstext: {
    position: "absolute",
    color: "white",
    fontFamily: "WorkSans-Bold",
    fontWeight: "700",
    fontSize: 16 / SCALE,
    textShadowColor: "rgba(0, 0, 0, 0.4)",
    textShadowOffset: { width: 2 / SCALE, height: 2 / SCALE },
    textShadowRadius: 6 / SCALE,
    height: 19 / SCALE,
    width: 87 / SCALE,
    lineHeight: 19 / SCALE,
    top: 5 / SCALE,
    paddingLeft: 1 / SCALE,
  },
  progresstext2: {
    textShadowColor: "rgba(255, 255, 255, 0.4)",
    textShadowOffset: { width: -2 / SCALE, height: -2 / SCALE },
  },
  exercisetrailername: {
    position: "absolute",
    height: 19 / SCALE,
    left: 10 / SCALE,
    top: 5 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 16 / SCALE,
    lineHeight: 19 / SCALE,
    color: "white",
  },
  exercisetrailerdots: {
    position: "absolute",
    width: 24 / SCALE,
    height: 24 / SCALE,
    left: 246 / SCALE,
    top: 3 / SCALE,
  },
  exercisetrailersets: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    position: "absolute",
    top: 28 / SCALE,
    left: 8 / SCALE,
    width: 264 / SCALE,
  },
  exercisepagetitle: {
    width: 250 / SCALE,
    height: 40 / SCALE,
    left: 10 / SCALE,
    fontFamily: "WorkSans-SemiBold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 20 / SCALE,
    lineHeight: 23 / SCALE,
    textAlign: "left",
    color: "white",
    margin: 0,
    padding: 0,
  },
  exercisepagepen: {
    position: "absolute",
    top: 10 / SCALE,
    width: 20 / SCALE,
    height: 20 / SCALE,
    left: 267 / SCALE,
  },
};

export default styles;
